PREFIX : "#!/bin/bash\n"

# Paths to engines
WASMTIME_PATH : "../wasmtime/target/release/wasmtime"
D8_PATH : "../v8/v8/out/x64.release/d8"
WIZARD_PATH : "../wizard-engine/bin/wizeng.x86-64-linux"

# Paths for building benchmarks
ASYNCIFY_DEFAULT_STACK_SIZE: 2097152
STACK_POOL_SIZE: 0
WASMFX_CONT_TABLE_INITIAL_CAPACITY: 1024
WASMFX_PRESERVE_SHADOW_STACK: 1
# Only relevant if WASMFX_PRESERVE_SHADOW_STACK is 1
WASMFX_CONT_SHADOW_STACK_SIZE: 65536
ASYNCIFY : "../binaryen/bin/wasm-opt --enable-exception-handling --enable-reference-types --enable-multivalue --enable-bulk-memory --enable-gc --enable-stack-switching -O2 --asyncify"
WASICC : "../benchfx/wasi-sdk-22.0/bin/clang"
WASIFLAGS : "--sysroot=../benchfx/wasi-sdk-22.0/share/wasi-sysroot -std=c17 -Wall -Wextra -Werror -Wpedantic -Wno-strict-prototypes -O3 -I inc"
WASM_INTERP : "../specfx/interpreter/wasm"
WASM_MERGE : "../binaryen/bin/wasm-merge --enable-multimemory --enable-exception-handling --enable-reference-types --enable-multivalue --enable-bulk-memory --enable-gc --enable-stack-switching"
SHADOW_STACK_FLAG : ""

# Paths to imports
WASMFX_IMPORTS : "wasmfx_imports.wasm"
V8_JS_LOADER : "load.mjs"