PREFIX : "#!/bin/bash\n"

# Paths to engines
WASMTIME_PATH : "../wasmtime/target/release/wasmtime"
D8_PATH : "../v8/v8/out/x64.release/d8"
WIZARD_PATH : "../wizard-engine/bin/wizeng.x86-64-linux"

# Paths for building benchmarks
ASYNCIFY_DEFAULT_STACK_SIZE: 2097152
STACK_POOL_SIZE: 0
WASMFX_CONT_TABLE_INITIAL_CAPACITY: 1024
WASMFX_PRESERVE_SHADOW_STACK: 1
WASMFX_CONT_SHADOW_STACK_SIZE: 65536
ASYNCIFY : "../binaryen/bin/wasm-opt --enable-exception-handling --enable-reference-types --enable-multivalue --enable-bulk-memory --enable-gc --enable-stack-switching -O2 --asyncify"

WASICC : "../wasi-sdk/build/install/bin/clang"
WASIFLAGS : "--sysroot=../wasi-sdk/build/install/share/wasi-sysroot -std=c17 -Wall -Wextra -Werror -Wpedantic -Wno-strict-prototypes  -O3 -I inc"
WASM_INTERP : "../specfx/interpreter/wasm"
WASM_MERGE : "../binaryen/bin/wasm-merge --enable-multimemory --enable-exception-handling --enable-reference-types --enable-multivalue --enable-bulk-memory --enable-gc --enable-stack-switching --enable-nontrapping-float-to-int"
SHADOW_STACK_FLAG : ""

# Paths to imports
WASMFX_IMPORTS : "wasmfx_imports.wasm"
V8_JS_LOADER : "load.mjs"

# Arguments for benchmarks
ITERSUM_ARGS : 1000000
TREESUM_ARGS : 20
SIEVE_ARGS : 2000